quarkus:
  devservices:
    enabled: true
  swagger-ui:
    always-include: true
    enable: true
    path: /swagger
  smallrye-openapi:
    open-api-version: "3.1.0"
    info-title: Validate API
    info-version: "1.0"
    info-description: Uma API responsável por notificar sobre o vencimento de produtos
    info-contact-email: gabrieladriano@furb.br, rbkretzer@furb.br, andreirobson@furb.br
  http:
    port: 9090
    cors: 
      ~: true
      access-control-allow-credentials: true
      origins: /.*/
      methods: GET, POST, PUT, DELETE, PATCH, OPTION, HEAD, TRACE, CONNECT
      headers: Access-Control-Allow-Headers, Accept, Content-Type, Authorization, X-Skip-Interceptor, X-Requested-With
  datasource:
    db-kind: postgresql
    username: postgresql
    password: root
    jdbc:
      url: 
  hibernate-orm:
    dialect: {org.hibernate.dialect.PostgreSQLDialect}
    database:
      generation: {update}
  flyway:
    migrate-at-start: true
    locations: db/migrations
gs1-brasil:
  url: https://api.gs1br.org/gs1
  client-id: clientId
  access-token: token